general {
    disable_loading_bar = false
    grace = 300
}

background {
    monitor =
    path = /path/to/your/wallpaper.png
    blur_passes = 2
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
}
